import function
# function.isPrime()
# print(function.reverse())
# print(function.k_rotate())
# print(function.merge_sortedlist())
# print(function.digit_list())
# print(function.remove_k_largest())
print(function.sort_list_bylength())
# print(function.sort_list_bylength_frequency())
# print(function.graph())
# print(function.matrix_mul())
